"""Build the WordPress announcement from verified product copy and saved media URLs."""
from pathlib import Path
import json
from PIL import Image
root=Path(__file__).parent
media=json.loads((root/'media.json').read_text())
canvas=json.loads((root/'canvas.json').read_text())
def figure(key,caption,framed=False):
    url=canvas[key]['url'] if framed else media[key]['source_url']
    width,height=(canvas[key]['width'],canvas[key]['height']) if framed else Image.open(root/'screenshots'/key).size
    return f'<figure class="cb-figure"><a href="{url}" target="_blank" rel="noopener"><img src="{url}" alt="{caption}" width="{width}" height="{height}" style="aspect-ratio:{width}/{height}" loading="lazy" decoding="async"></a><figcaption>{caption} Click to enlarge.</figcaption></figure>'
def setupfigure(key,caption):
    return figure(key,caption)
html='''<style>
.cb-launch{max-width:1000px;margin:0 auto;color:#1d1d22;font-family:Inter,Arial,sans-serif;font-size:18px;line-height:1.8}.cb-launch *{box-sizing:border-box}.cb-launch h2{font-family:Cardo,Georgia,serif;font-weight:400;font-size:40px;line-height:1.2;margin:64px 0 24px;letter-spacing:-.6px}.cb-launch h3{font-size:23px;line-height:1.4;margin:32px 0 14px}.cb-launch p{margin:0 0 22px}.cb-launch a{color:#027ba6}.cb-launch .cb-lead{font-size:23px;line-height:1.65}.cb-kicker{font-size:13px;letter-spacing:2px;text-transform:uppercase;color:#027ba6;font-weight:600}.cb-launch .cb-callout{background:#f5fbfd;border-left:3px solid #027ba6;padding:28px 32px;margin:32px 0}.cb-launch .cb-callout p:last-child{margin-bottom:0}.cb-launch .cb-figure{margin:36px 0 44px}.cb-launch .cb-figure img{width:100%;height:auto;display:block;border:1px solid #e5e5e9;border-radius:12px}.cb-launch figcaption{font-size:13px;line-height:1.6;color:#61616c;padding:12px 2px}.cb-launch .cb-note{font-size:14px;color:#61616c}.cb-launch .cb-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin:28px 0}.cb-launch .cb-card{padding:24px;border:1px solid #e5e5e9;border-radius:12px;background:#fff}.cb-launch .cb-card h3{margin-top:0}.cb-launch .cb-card p{margin:0;font-size:16px}.cb-launch .cb-setup-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;align-items:start}.cb-launch .cb-setup-grid figure{margin-top:12px}.cb-launch .cb-cta{background:#f5fbfd;border:1px solid #cef0ff;padding:36px;border-radius:16px;margin:52px 0}.cb-launch .cb-cta h2{margin:0 0 18px}.cb-launch .cb-button{display:inline-block;background:#027ba6;color:white!important;padding:12px 25px;border-radius:7px;text-decoration:none;font-size:16px;font-weight:600}.cb-launch li{margin-bottom:12px}.cb-launch code{font-size:15px;overflow-wrap:anywhere}@media(max-width:680px){.cb-launch{font-size:17px}.cb-launch h2{font-size:32px;margin-top:44px}.cb-launch .cb-lead{font-size:20px}.cb-launch .cb-grid,.cb-launch .cb-setup-grid{grid-template-columns:1fr}.cb-launch .cb-callout,.cb-launch .cb-cta{padding:24px}.cb-launch .cb-figure{margin:26px 0}}
</style><article class="cb-launch">
<p class="cb-kicker">Product announcement · Company Brain Beta</p>
<p class="cb-lead">Your next great customer conversation should start with everything you already know.</p>
<p>A prospect replies to an email. A colleague from the same company books a meeting. Another contact has been talking to your website agent. The details are valuable—but only if you can connect them before the next conversation.</p>
<p>Meet <strong>Company Brain</strong>, the relationship intelligence layer inside Parallel AI. It brings people, companies, source records, and activity into a connected view, so you can understand who someone is, where your team knows them from, and what has happened so far.</p>
<p>Open a person. Follow the context. See the company behind the conversation. Spend less time reconstructing the story and more time moving it forward.</p>
<div class="cb-callout"><p><strong>Start here:</strong> Open your company workspace, expand <strong>Find &amp; Enrich</strong>, and select <strong>Company Brain</strong>. Your internal sources already contribute. Add a CRM and meeting activity from Settings when you are ready.</p><p><a href="#company-brain-setup">Jump to the setup walkthrough ↓</a></p></div>
<p class="cb-note">The screenshots below show actual Company Brain components in light mode, populated in a local demonstration workspace. All people, companies, messages, counts, and connection states are fictional examples—not customer records or performance results.</p>
<h2>One person. A much richer picture.</h2>
<p>The same person can appear in a Smart List, an outreach sequence, your inbox, a campaign, and your CRM. Company Brain resolves those records into a shared person profile and keeps the connected sources visible.</p>
<p>The directory puts names, roles, companies, source connections, and latest engagement together. Search by person, company, email, or phone; narrow by source; and move between <strong>Everyone</strong>, <strong>Engaged</strong>, <strong>Not yet engaged</strong>, and <strong>Needs review</strong>. Sort by latest engagement or alphabetically.</p>
<p>On a wide screen, selecting a row opens a relationship brief beside the directory. You can see the latest signal and source breakdown without losing your place, then open the full profile when you need more detail.</p>
'''+figure('directory','The people directory combines relationship context, source counts, and latest engagement. Fictional demo data.',True)+'''
<h2>Walk into the next conversation prepared.</h2>
<p>Imagine Maya Chen, VP of Operations at the fictional Harborline Systems. She entered through an operations Smart List, received a workflow introduction, clicked a resource, and replied asking to include two colleagues in a walkthrough.</p>
<p>Her profile brings that story together: contact details, role, company information, engagement, and the source records behind it. Where the underlying data is available, you can inspect Smart List fields, see messages sent in a sequence, and open the retained reply text.</p>
<p>That changes the next follow-up. Instead of sending another generic introduction, you can continue the discussion Maya already started—with the right colleagues and the right context.</p>
'''+figure('profile','Maya’s profile shows her reply, meeting booking, company details, and connected records. Fictional demo data.',True)+'''
<h2>Find the signals that deserve your attention.</h2>
<p>Activity and engagement answer different questions. Company Brain gives you both perspectives.</p>
<div class="cb-grid"><div class="cb-card"><h3>Engagement</h3><p>See human replies, shared-inbox inbound messages, messages to your agents, and bot-filtered sequence clicks, scheduling-page views, and bookings. The directory uses these signals to surface recent engagement.</p></div><div class="cb-card"><h3>All activity</h3><p>Explore detailed sequence tracking history: opens, clicks, scheduling views, bookings, completed calls, and status changes. Filter event types and inspect their timestamps in chronological context.</p></div></div>
<p><strong>Sending more messages does not make a person more engaged.</strong> Sends and opens do not drive the engagement ranking. Detected security-scanner and mail-proxy traffic is excluded by default from the detailed activity view; its Automated toggle lets you inspect the events held back.</p>
'''+figure('03-activity.png','The All activity tab shows event filters, precise timestamps, and an Automated traffic toggle. Fictional demo data.')+'''
<p class="cb-note">Coverage depends on the source. The detailed All activity view currently centers on sequence tracking; campaign counters and website-pixel records are not presented as a complete per-visit event stream. Bot filtering reduces known automated noise; it is not a guarantee that every remaining signal reflects buying intent.</p>
<h2>See the account around the contact.</h2>
<p>Business relationships rarely stop at one person. Click a company from the directory or a person’s profile to open its <strong>Company network</strong>.</p>
<p>The interactive graph connects the company to its people and the sources behind those relationships. Zoom, focus on an account, inspect review status, and open a person’s profile from the graph.</p>
<p>In our Harborline example, Maya in operations, Avery on the delivery team, and Morgan in IT become part of one visible account story. You can see the contacts and their connected evidence without treating every lead as an isolated row.</p>
'''+figure('network','Harborline’s company network connects three people to their underlying source records. Fictional demo data.',True)+'''
<h2>Trust the context because you can inspect it.</h2>
<p>Identity matching needs transparency. In a person’s <strong>Data sources</strong> tab, Company Brain shows the identifiers used to connect records and the number of links associated with each key.</p>
<p>Use <strong>Needs review</strong> to find profiles with uncertain identity evidence. Check the email addresses, phone numbers, or name-and-company matches before confirming that they belong to the same person. A shared or incorrect identifier can be disabled for future matching while remaining visible for reference. New ambiguous evidence can require another review.</p>
'''+figure('05-identity.png','Data sources &amp; matching makes the identity evidence visible and provides review controls. Fictional demo data.')+'''
<h2>Bring more of your business into the picture.</h2>
<p>Parallel AI’s native sources—Smart Lists, sequences, campaigns, agent conversations, and inbox activity—already contribute to Company Brain. You can extend that context with a selected CRM connection and supported meeting apps.</p>
<ul><li><strong>CRM contacts:</strong> Choose one connected CRM as the source for people and company data. Supported providers in the current implementation include HubSpot, Salesforce, and GoHighLevel.</li><li><strong>Google Calendar:</strong> Enable sync to bring events from readable calendars into the identity graph for matching external invitees.</li><li><strong>Zoom:</strong> Bring in past meetings when client attendees can be identified from the participant data available to your connected account.</li><li><strong>Your own workflows:</strong> The People API supports finding resolved people, retrieving profiles and the company graph, and adding, listing, updating, or deleting custom text activities. Supply a source and external ID when creating an activity to make repeated submissions idempotent.</li></ul>
<p>A custom activity might capture a completed product walkthrough, an onboarding milestone, or a service handoff. This gives developers a way to attach business-specific context to a resolved person. Custom activities and synced meeting records are separate from the sequence tracking stream shown in All activity.</p>
<h2 id="company-brain-setup">Get started: find it, connect it, explore it.</h2>
<h3>1. Open Company Brain in the right workspace.</h3>
<p>Sign in to Parallel AI and select the company you want to work in. In the sidebar, expand <strong>Find &amp; Enrich</strong> and select <strong>Company Brain</strong>, currently marked Beta.</p>
<p>The setup guide introduces the identity graph and your sources. You can reopen it from the <strong>question-mark icon</strong> beside the Company Brain action row. Choose <strong>Explore</strong> to enter the directory.</p>
'''+figure('06-tutorial.png','The built-in guide explains native sources, CRM selection, and meeting activity setup. Fictional demo workspace.')+'''
<h3>2. Check your sources and select a CRM.</h3>
<p>Open <strong>Settings → Sources</strong>. Internal activity is always on. If you want CRM data, choose the relevant connection under <strong>CRM connections</strong>; your selection saves immediately. You can select one CRM connection at a time.</p>
<p>If none appears, go to your company’s <strong>Settings → Integrations</strong>, connect a supported CRM, and return to Company Brain. Back in <strong>Company Brain → Settings</strong>, use <strong>Sync now</strong> to queue a people sync. Allow processing time before expecting imported records to appear.</p>
<div class="cb-setup-grid">'''+setupfigure('09-settings.png','Company Brain settings: people sync, activity sync, and data sources.')+setupfigure('07-sources.png','Select one connected CRM. Connection names and states shown here are fictional.')+'''</div>
<h3>3. Enable Calendar or Zoom activity.</h3>
<p>Open <strong>Settings → Activity sync → Configure</strong>. In Connected apps, select a Google Calendar or Zoom account. Use <strong>Connect</strong> if you need to add one, then <strong>Enable</strong> to turn on its sync.</p>
<p>Once enabled, the card shows <strong>Sync</strong>, <strong>Pause</strong>, and the last sync time. Use these controls to refresh or pause the connection. Matching depends on the attendee information the app supplies; not every meeting will identify a client.</p>
<div style="max-width:600px;margin:0 auto">'''+setupfigure('08-sync.png','Google Calendar and Zoom sync controls with fictional connected accounts.')+'''</div>
<h3>4. Follow one relationship from start to finish.</h3>
<ol><li>Search for a person or company in the directory.</li><li>Select a row to inspect its relationship brief, or click the person’s name for the full profile.</li><li>Read <strong>Engagement</strong> for recent human signals and <strong>All activity</strong> for the detailed sequence history.</li><li>Open <strong>Data sources</strong> to understand how the records were connected.</li><li>Click the company name to explore its network and the other people involved.</li></ol>
<div class="cb-callout"><p><strong>A useful first exercise:</strong> Pick an account you are actively speaking with. Find the latest reply, identify the other people at that company, and review the sources behind the relationship. You now have a concrete starting point for your next conversation.</p></div>
<h2>Built for the moments when context matters.</h2>
<div class="cb-grid"><div class="cb-card"><h3>Before a sales call</h3><p>Review the latest reply, clicked resource, and people connected to the account before you join.</p></div><div class="cb-card"><h3>During a handoff</h3><p>Give the next teammate a profile with the source records and conversation history behind the relationship.</p></div><div class="cb-card"><h3>When prioritizing follow-up</h3><p>Start with recent human engagement, then inspect the actual interaction before deciding what to do next.</p></div><div class="cb-card"><h3>When cleaning up context</h3><p>Review uncertain identities and disable shared matching keys so future connections use better evidence.</p></div></div>
<div class="cb-cta"><h2>Your relationships already have a story.</h2><p>Company Brain helps you see it. Open your workspace, connect the sources that matter, and turn the next conversation into a continuation.</p><a class="cb-button" href="https://web.parallellabs.app/dashboard/companies">Explore</a><p class="cb-note" style="margin-top:16px;margin-bottom:0">Choose your company, then Find &amp; Enrich → Company Brain.</p></div>
<p class="cb-note">Product screens captured from the application’s existing components using fictional fixtures. Branded artwork created with Parallel AI Canvas. Scenery photography: Ali Kazal, Adrian Newell, Wilson Rodriguez, and Vietnam Photographer via Pexels.</p>
</article>'''
(root/'article.html').write_text(html)
post={'title':'Introducing Company Brain: Every Relationship, One Connected Story','slug':'introducing-company-brain','status':'draft','content':html,'excerpt':'Meet Company Brain: connect people, companies, conversations, and activity in Parallel AI. See the feature in action and follow the step-by-step setup guide.','categories':[68,160],'comment_status':'closed'}
# Populated after the Canvas hero has been imported into WordPress.
if (root/'hero-media.json').exists(): post['featured_media']=json.loads((root/'hero-media.json').read_text())['id']
(root/'post.json').write_text(json.dumps(post,indent=2))
print('Article and WordPress payload saved.')
